config/routes.rb
Rails.application.routes.draw do
	authenticated :user do
		root to: 'users#show', as: :authenticated_root
	end

	devise_for :users, controllers: { registrations: "users/registrations" } 
	devise_scope :user do
	  get "signin", to: "devise/sessions#new", as: "signin"
	  get "free-trial", to: "users/registrations#new", as: "free_trial"
	end
	resources :users do
		member do
			get 	'tag'
			get 	'rack'
			get 	'remember_rack'
			get		'forget_rack'
			patch 'confirm_password'
			get 	'lost_receipt'
			get 	'read_intro'
			get 	'read_tutorial'
			patch 'set_rack'
		end
	end
	match '/:id/urgent', to: 'users#urgent', via: 'get', as: 'urgent'
	match '/:id/products', to: 'users#products', via: 'get', as: 'user_products'
	match '/:id/employees', to: 'users#employees', via: 'get', as: 'user_employees'
	match '/:id/analytics', to: 'users#analytics', via: 'get', as: 'user_analytics'

	root to: 'pages#home'
	match '/terms', to: 'pages#terms', via: 'get', as: 'terms'

	resources :customers do
		collection { post :import }
		member do
			patch 'update_name'
			patch 'update_phone'
			patch 'update_text'
			patch 'update_starch'
			get 	'place_order'
			get		'details'
			get		'order_history'
			get 	'checkout'
			get		'pay_with_cash'
			get		'productless_item'
			get		'charge_later'
			get 	'pay_with_card'
		end
	end

	resources :products do
		member do
			get 'load_edit'
		end
	end

	resources :categories

	resources :items do
		member do
			patch 'update_price'
		end
	end

	resources :orders do
		member do
			get 	'details'
			get 	'pick_up'
			get 	'search_rack'
			get 	'search_tags'
			get 	'add_order_number'
			get 	'print_receipt'
			patch 'rack'
			get 	'confirm_delete'
			patch 'delete_order'
			get		'pay_on_pickup'
			patch 'leave_note'
			get		'load_urgent_rack'
			patch 'rack_urgent_order'
			get		'pickup_pay_with_cash'
			get		'pickup_pay_with_card'
		end
	end

	resources :cards do
		member do
			get 'pay'
			get 'pickup_pay'
		end
	end

	resources :employees

	resources :checkins do
		member do
			get 	'show_more'
			get 	'change_start_time'
			get 	'change_finish_time'
			patch 'update_start_time'
			patch 'update_finish_time'
		end
	end

	resources :tutorials do
		member do
			get 'open'
		end

		collection do
			post 'sort'
		end
	end
	match '/tutorial', to: 'tutorials#user_tutorial', via: 'get', as: 'user_tutorial'

	resources :messages
end

app/models/employee.rb
class Employee < ActiveRecord::Base
	#validations
	validates :name, presence: true
	validates :phone, presence: true, numericality: true
	validates :user_id, presence: true, numericality: true
	validates :pay_rate, presence: true, numericality: true

	#relationships
	belongs_to :user
	has_many :checkins

	#scopes
	scope :recently, -> {order("created_at DESC")}
end

app/controllers/employees_controller.rb
class EmployeesController < ApplicationController
	def create
		@employee = Employee.new(employee_params)
		@saved = @employee.save
		respond_to do |format|
			format.js
		end
	end

	def show
		@employee = Employee.find(params[:id])
		@checkins = @employee.checkins.recently.take(10)
		respond_to do |format|
			format.js
		end
	end

	def edit
		@employee = Employee.find(params[:id])
		respond_to do |format|
			format.js
		end
	end

	def update
		@employee = Employee.find(params[:id])
		@checkins = @employee.checkins.recently.take(10)
		@updated = @employee.update_attributes(employee_params)
		respond_to do |format|
			format.js
		end
	end

	private
		def employee_params
			params.require(:employee).permit(:name, :phone, :user_id, :pay_rate)
		end
end

app/helpers/employees_helper.rb
module EmployeesHelper
	#assign correct root path based on whether user is logged in yet
	def assign_root_path
		if signed_in?
			user_path(current_user)
		else
			root_path
		end
	end
end

app/views/employees/_edit.html.erb
<div id="modal-overlay">
	<%= simple_form_for current_user, url: confirm_password_user_path(current_user), html: {id: "confirm-password"}, remote: true do |f| %>
	  <%= password_field_tag "password", nil, placeholder:"Enter Password" %>
	  <%= submit_tag "Confirm Password" %>

	  <!-- exit this form -->
		<span class="exit-form"><i class='fa fa-times'></i></span>
	<% end %>

	<!-- create new employee -->
	<%= simple_form_for @employee, remote: true, html: {class: "hide edit_employee"} do |f| %>
		<%= f.input :name, placeholder: "Employee Name", label: false %>
		<%= f.input :phone, placeholder: "Phone Number", label: false %>
		<%= f.input :pay_rate, placeholder: "Pay Rate ($/hr)", label: false %>
		<%= f.submit "Update Employee" %>

		<!-- exit this form -->
		<span class="exit-form"><i class='fa fa-times'></i></span>
	<% end %>
</div>

app/views/employees/_employee.html.erb
<%= link_to employee_path(employee), class: "employee employee-#{employee.id}", remote: true do %>
	<%= employee.name %>
<% end %>

app/views/employees/_timesheet.html.erb
<div id="timesheet" class="timesheet-<%= @employee.id %>">
	<div class="exit-timesheet">
		<span class="employee-name"><%= @employee.name %></span>

		<i class='fa fa-times'></i>

		<div style="clear:both;"></div>
	</div>

	<% if !@employee.checkins.where("finish IS NULL").any? %>
		<%= render 'checkins/new_checkin' %>
	<% else %>
		<%= render 'checkins/check_out' %>
	<% end %>

	<% if @checkins.any? %>
		<table id="checkin-list">
			<tr>
				<th>Date</th>
				<th>Start</th>
				<th>Finish</th>
				<th>Total</th>
			</tr>
			<%= render @checkins %>
		</table>

		<% if @employee.checkins.count > @checkins.count %>
			<%= link_to show_more_checkin_path(@checkins.last), remote: true, class: "show-more" do %>
				Show More <i class='fa fa-caret-down'></i>
			<% end %>
		<% end %>
	<% end %>

	<%= link_to "Edit Settings", edit_employee_path(@employee), remote: true, class: "edit-employee-link" %>
</div>

app/views/employees/create.js.erb
<% if @saved %>
	//clear new employee form and hide
	$("#new_employee")[0].reset();
	$("#modal-overlay").fadeOut();

	//add new employee to employee list
	$("#employee-list").prepend("<%= j render @employee %>");

	//update title
	$("title").html("Incrediclean | <%= pluralize(@employee.user.employees.count, 'employee') %>");
<% end %>

app/views/employees/edit.js.erb
//load modal to edit employee
$("#user-employees-container").prepend("<%= j render 'employees/edit' %>");
//autofocus on confirm password field
$("#confirm-password input[type='password']").focus();

app/views/employees/show.js.erb
//exit out of previous timesheet if there's one open
if($("#timesheet")[0]){
	$("#timesheet").prev(".employee").show();
	$("#timesheet").remove();
}
//hide employee link
$(".employee-<%= @employee.id %>").hide();
//load employee timesheet
$(".employee-<%= @employee.id %>").after("<%= j render 'employees/timesheet' %>");

//scroll to top of newly loaded timesheet
$('html, body').animate({
	scrollTop: $(".timesheet-<%= @employee.id %>").offset().top
}, 150);

app/views/employees/update.js.erb
<% if @updated %>
	//remove edit employee form
	$(".edit_employee").parent("#modal-overlay").fadeOut(function(){
		$(".edit_employee").parent("#modal-overlay").remove();
	});

	//replace updated employee
	$(".employee-<%= @employee.id %>").replaceWith("<%= j render @employee %>");
	$(".employee-<%= @employee.id %>").hide();
	$("#timesheet").replaceWith("<%= j render 'employees/timesheet' %>");
<% end %>