config/routes.rb
Rails.application.routes.draw do
	authenticated :user do
		root to: 'users#show', as: :authenticated_root
	end

	devise_for :users, controllers: { registrations: "users/registrations" } 
	devise_scope :user do
	  get "signin", to: "devise/sessions#new", as: "signin"
	  get "free-trial", to: "users/registrations#new", as: "free_trial"
	end
	resources :users do
		member do
			get 	'tag'
			get 	'rack'
			get 	'remember_rack'
			get		'forget_rack'
			patch 'confirm_password'
			get 	'lost_receipt'
			get 	'read_intro'
			get 	'read_tutorial'
			patch 'set_rack'
		end
	end
	match '/:id/urgent', to: 'users#urgent', via: 'get', as: 'urgent'
	match '/:id/products', to: 'users#products', via: 'get', as: 'user_products'
	match '/:id/employees', to: 'users#employees', via: 'get', as: 'user_employees'
	match '/:id/analytics', to: 'users#analytics', via: 'get', as: 'user_analytics'

	root to: 'pages#home'
	match '/terms', to: 'pages#terms', via: 'get', as: 'terms'

	resources :customers do
		collection { post :import }
		member do
			patch 'update_name'
			patch 'update_phone'
			patch 'update_text'
			patch 'update_starch'
			get 	'place_order'
			get		'details'
			get		'order_history'
			get 	'checkout'
			get		'pay_with_cash'
			get		'productless_item'
			get		'charge_later'
			get 	'pay_with_card'
		end
	end

	resources :products do
		member do
			get 'load_edit'
		end
	end

	resources :categories

	resources :items do
		member do
			patch 'update_price'
		end
	end

	resources :orders do
		member do
			get 	'details'
			get 	'pick_up'
			get 	'search_rack'
			get 	'search_tags'
			get 	'add_order_number'
			get 	'print_receipt'
			patch 'rack'
			get 	'confirm_delete'
			patch 'delete_order'
			get		'pay_on_pickup'
			patch 'leave_note'
			get		'load_urgent_rack'
			patch 'rack_urgent_order'
			get		'pickup_pay_with_cash'
			get		'pickup_pay_with_card'
		end
	end

	resources :cards do
		member do
			get 'pay'
			get 'pickup_pay'
		end
	end

	resources :employees

	resources :checkins do
		member do
			get 	'show_more'
			get 	'change_start_time'
			get 	'change_finish_time'
			patch 'update_start_time'
			patch 'update_finish_time'
		end
	end

	resources :tutorials do
		member do
			get 'open'
		end

		collection do
			post 'sort'
		end
	end
	match '/tutorial', to: 'tutorials#user_tutorial', via: 'get', as: 'user_tutorial'

	resources :messages
end

app/models/tutorial.rb
class Tutorial < ActiveRecord::Base
	#automatically increment position
	acts_as_list
	
	#validations
	validates :title, presence: true
	validates :video, presence: true

	#scopes
	scope :by_position, -> {order("position")}
end

app/controllers/tutorials_controller.rb
class TutorialsController < ApplicationController
	def open
		@tutorial = Tutorial.find(params[:id])
		respond_to do |format|
			format.js
		end
	end

	def user_tutorial
		@tutorials = Tutorial.by_position
	end

	def show
		@tutorial = Tutorial.find(params[:id])
	end

	def index
		if current_user && current_user.admin
			@tutorials = Tutorial.by_position
		else
			redirect_to root_path
		end
	end

	def create
		@tutorial = Tutorial.new(tutorial_params)
		@saved = @tutorial.save
		respond_to do |format|
			format.js
		end
	end

	def update
		@tutorial = Tutorial.find(params[:id])
		@tutorials = Tutorial.by_position
		@updated = @tutorial.update_attributes(tutorial_params)
		respond_to do |format|
			format.js
		end
	end

	def sort
		params[:tutorial].each_with_index do |id, index|
			Tutorial.where(id: id).update_all(position: index+1)
	  end

	  @tutorials = Tutorial.by_position
	  
	  respond_to do |format|
	  	format.js
	  end
	end

	private
		def tutorial_params
			params.require(:tutorial).permit(:title, :transcript, :video, :position)
		end
end

app/views/tutorials/_tutorial.html.erb
<%= content_tag_for :li, tutorial do %>
	<%= link_to tutorial_path(tutorial), remote: true do %>
		<span>00<%= tutorial.position %></span> <%= tutorial.title %>
	<% end %>
<% end %>

app/views/tutorials/_tutorial_details.html.erb
<div class='tutorial-details'>
	<div class="exit-tutorial-container">
		<span class="tutorial-title"><%= @tutorial.title %></span>

		<i class='fa fa-times exit-button'></i>

		<div style="clear:both;"></div>
	</div>

	<div class='edit-tutorial-section'>
		<div class="video-wrapper">
			<iframe type="text/html" src="//www.youtube.com/embed/<%= @tutorial.video %>" frameborder="0" allowfullscreen></iframe>
		</div>

		<%= simple_form_for @tutorial, remote: true, html: {id: "edit-tutorial-#{@tutorial.id}"} do |f| %>
			<%= f.input :title, label: false, placeholder: "Title", input_html: {class: "default-input"} %>
			<%= f.input :video, placeholder: "Youtube Video URL", label: false, input_html: {class: "default-input"} %>

			<%= f.submit "Update Tutorial", class: "black-button" %>
		<% end %>
	</div>
</div>

app/views/tutorials/_video.html.erb
<div class='tutorial-video'>
	<div class='exit-tutorial-container'>
		<span class='tutorial-title'><%= @tutorial.title %></span>

		<i class='fa fa-times exit-button'></i>

		<div style="clear:both;"></div>
	</div>

	<div class="video-wrapper">
		<iframe type="text/html" src="//www.youtube.com/embed/<%= @tutorial.video %>" frameborder="0" allowfullscreen></iframe>
	</div>
</div>

app/views/tutorials/create.js.erb
<% if @saved %>
	//prepend new tutorial to tutorial list
	$("#tutorial-list").prepend("<%= j render @tutorial %>");
	//clear and hide new tutorial form
	$("#new_tutorial")[0].reset();
	$("#new_tutorial").parent("#modal-overlay").fadeOut();
	$(".add-tutorial-video").html("<i class='fa fa-video-camera'></i>");
<% end %>

app/views/tutorials/edit.js.erb
//load form to edit tutorial
$("#tutorials-container").prepend("<%= j render 'tutorials/edit_tutorial' %>");
//autofocus on title
$(".edit_tutorial #tutorial_title").focus();

tinyMCE.editors[0].editorManager.remove();
tinymce.init({
  selector: "textarea",
  toolbar: "styleselect | bold italic underline | bullist numlist outdent indent",
  height: 300
});

app/views/tutorials/index.html.erb
<% provide(:title, pluralize(@tutorials.count, "tutorial")) %>

<div id="tutorials-container">
	<div class='add-tutorial-button'>+</div>

	<ul id="tutorial-list" data-update-url="<%= sort_tutorials_url %>">
		<%= render @tutorials %>
	</ul>

	<div id="modal-overlay" class="hide">
		<!-- create new customer -->
		<%= simple_form_for Tutorial.new, remote: true do |f| %>
			<%= f.input :title, placeholder: "Title", label: false %>
			<%= f.input :video, placeholder: "Youtube Video URL", label: false %>

			<%= f.submit "+ Add Tutorial" %>

			<!-- exit this form -->
			<span class="exit-form">
				<i class='fa fa-times'></i>
			</span>
		<% end %>
	</div>
</div>

app/views/tutorials/open.js.erb
//hide previously opened tutorial videos to keep shit clear
if($(".tutorial-video")[0]){
	$(".tutorial-video").prev(".user-tutorial").show();
	$(".tutorial-video").remove();
}

//hide tutorial
$(".user-tutorial-<%= @tutorial.id %>").hide();
//load tutorial video underneath tutorial
$(".user-tutorial-<%= @tutorial.id %>").after("<%= j render 'tutorials/video' %>");

app/views/tutorials/show.js.erb
//hide previously opened tutorials
if($('.tutorial:hidden')[0]){
	$('.tutorial:hidden').next('.tutorial-details').remove();
	$('.tutorial:hidden').show();
}

//hide link and load form to edit tutorial videos
$("#tutorial_<%= @tutorial.id %>").hide();
$("#tutorial_<%= @tutorial.id %>").after("<%= j render 'tutorials/tutorial_details' %>");

//autofocus on title
$("#edit-tutorial-<%= @tutorial.id %> #tutorial_title").focus();

app/views/tutorials/sort.js.erb
//update entire tutorial list
$("#tutorial-list").html("<%= j render @tutorials %>");

app/views/tutorials/update.js.erb
<% if @updated %>
	//revive tutorial list
	$("#tutorial-list").html("<%= j render @tutorials %>");
<% end %>

app/views/tutorials/user_tutorial.html.erb
<% provide(:title, "#{pluralize(@tutorials.count, 'tutorial')}") %>

<div class='page-header'>
	<div class='header-h1'>Tutorials</div>
	<ul class='page-header-links'>
		<!-- contact -->
		<li><%= render 'layouts/help_me' %></li>
	</ul>
</div>

<div id="user-tutorial-container" class='inner-container'>

	<% @tutorials.each do |tutorial| %>
		<%= link_to open_tutorial_path(tutorial), remote: true, class: "user-tutorial user-tutorial-#{tutorial.id}" do %>
			<span>00<%= tutorial.position %></span>
			<%= tutorial.title %>
		<% end %>
	<% end %>
</div>