config/routes.rb
Rails.application.routes.draw do
	authenticated :user do
		root to: 'users#show', as: :authenticated_root
	end

	devise_for :users, controllers: { registrations: "users/registrations" } 
	devise_scope :user do
	  get "signin", to: "devise/sessions#new", as: "signin"
	  get "free-trial", to: "users/registrations#new", as: "free_trial"
	end
	resources :users do
		member do
			get 	'tag'
			get 	'rack'
			get 	'remember_rack'
			get		'forget_rack'
			patch 'confirm_password'
			get 	'lost_receipt'
			get 	'read_intro'
			get 	'read_tutorial'
			patch 'set_rack'
		end
	end
	match '/:id/urgent', to: 'users#urgent', via: 'get', as: 'urgent'
	match '/:id/products', to: 'users#products', via: 'get', as: 'user_products'
	match '/:id/employees', to: 'users#employees', via: 'get', as: 'user_employees'
	match '/:id/analytics', to: 'users#analytics', via: 'get', as: 'user_analytics'

	root to: 'pages#home'
	match '/terms', to: 'pages#terms', via: 'get', as: 'terms'

	resources :customers do
		collection { post :import }
		member do
			patch 'update_name'
			patch 'update_phone'
			patch 'update_text'
			patch 'update_starch'
			get 	'place_order'
			get		'details'
			get		'order_history'
			get 	'checkout'
			get		'pay_with_cash'
			get		'productless_item'
			get		'charge_later'
			get 	'pay_with_card'
		end
	end

	resources :products do
		member do
			get 'load_edit'
		end
	end

	resources :categories

	resources :items do
		member do
			patch 'update_price'
		end
	end

	resources :orders do
		member do
			get 	'details'
			get 	'pick_up'
			get 	'search_rack'
			get 	'search_tags'
			get 	'add_order_number'
			get 	'print_receipt'
			patch 'rack'
			get 	'confirm_delete'
			patch 'delete_order'
			get		'pay_on_pickup'
			patch 'leave_note'
			get		'load_urgent_rack'
			patch 'rack_urgent_order'
			get		'pickup_pay_with_cash'
			get		'pickup_pay_with_card'
		end
	end

	resources :cards do
		member do
			get 'pay'
			get 'pickup_pay'
		end
	end

	resources :employees

	resources :checkins do
		member do
			get 	'show_more'
			get 	'change_start_time'
			get 	'change_finish_time'
			patch 'update_start_time'
			patch 'update_finish_time'
		end
	end

	resources :tutorials do
		member do
			get 'open'
		end

		collection do
			post 'sort'
		end
	end
	match '/tutorial', to: 'tutorials#user_tutorial', via: 'get', as: 'user_tutorial'

	resources :messages
end

app/models/card.rb
class Card < ActiveRecord::Base
	#validations
	validates :last4, presence: true
	validates :brand, presence: true
	validates :stripe_customer_token, presence: true
	validates :customer_id, presence: true

	#relationships
	belongs_to :customer
	has_many :orders

	#scopes
	scope :recently, -> {order("created_at DESC")}

	def charge_new_card_on_pickup(order)
		customer = self.customer

		#create customer
  	stripe_customer = Stripe::Customer.create(
		  description: customer.name,
		  card: self.stripe_card_token
		)

		#save stripe customer token to card
    self.stripe_customer_token = stripe_customer.id
    self.pickup = false

    #save values from charge
	  stripe_card = stripe_customer.cards.retrieve(Stripe::Customer.retrieve(self.stripe_customer_token).default_card)
	  self.brand = stripe_card.brand
	  self.last4 = stripe_card.last4

    save!

    self.charge_card_on_pickup(order)
	rescue Stripe::InvalidRequestError => e
	  logger.error "Stripe error while creating customer: #{e.message}"
	  errors.add :base, "There was a problem with your credit card."
	  false
	end

	def charge_card_on_pickup(order)
		card = self

		total = order.total

		#create charge
	  charge = Stripe::Charge.create(
		  amount: (total*100.0).to_i,
		  currency: "usd",
		  customer: card.stripe_customer_token,
		  description: "Charged #{customer.name} $#{total}"
		)

		#mark items and order as paid and add to order
		order.update_attributes(paid:true, picked_up:true, pickup_time:DateTime.now, card_id: self.id)

		#items that belong to order but are not paid yet
		unpaid_items = order.items

		unpaid_items.update_all(paid:true)

		#change products' sold field
		unpaid_items.each do |item|
			if item.product_id
				product = item.product
				product.sold += item.quantity
				product.save
			end
		end
	rescue Stripe::InvalidRequestError => e
	  logger.error "Stripe error while creating customer: #{e.message}"
	  errors.add :base, "There was a problem with your credit card."
	  false
	end

	def charge_card
		customer = self.customer
		user = customer.user

		#calculate order total
		unpaid_items = customer.items.not_paid.orderless
    total = 0

    unpaid_items.each do |item|
    	total += (item.quantity * item.price)
    end

		#create charge
	  charge = Stripe::Charge.create(
		  amount: (total*100.0).to_i,
		  currency: "usd",
		  customer: self.stripe_customer_token,
		  description: "Charged #{customer.name} $#{total}"
		)

	  #create order
		order = Order.create(total: total, customer_id: customer.id, user_id: user.id, card_id: self.id, paid: true, pickup_time: 3.business_days.after(DateTime.now))
		order.save

		#mark items as paid and add to order
		unpaid_items.update_all(paid:true, order_id:order.id, created_at: order.created_at)

		#change products' sold field
		unpaid_items.each do |item|
			if item.product_id
				product = item.product
				product.sold += item.quantity
				product.save
			end
		end
	rescue Stripe::InvalidRequestError => e
	  logger.error "Stripe error while creating customer: #{e.message}"
	  errors.add :base, "There was a problem with your credit card."
	  false
	end

	def charge_new_card
		customer = self.customer

		#create customer
  	stripe_customer = Stripe::Customer.create(
		  description: customer.name,
		  card: self.stripe_card_token
		)

		#save stripe customer token to card
    self.stripe_customer_token = stripe_customer.id

    #save values from charge
	  stripe_card = stripe_customer.cards.retrieve(Stripe::Customer.retrieve(self.stripe_customer_token).default_card)
	  self.brand = stripe_card.brand
	  self.last4 = stripe_card.last4

    save!

    self.charge_card
	rescue Stripe::InvalidRequestError => e
	  logger.error "Stripe error while creating customer: #{e.message}"
	  errors.add :base, "There was a problem with your credit card."
	  false
	end
end

app/controllers/cards_controller.rb
class CardsController < ApplicationController
	def destroy
		@card = Card.find(params[:id])
		@destroyed = @card.destroy
		respond_to do |format|
			format.js
		end
	end

	def create
		@card = Card.new(card_params)
		@customer = @card.customer
		@user = @customer.user
		
		Stripe.api_key = @card.customer.user.stripe_secret_key

		unless params[:order_id]
			@card.charge_new_card
			@order = @card.orders.recently.first
			@saved_on_dropoff = true
		else
			@order = Order.find(params[:order_id])
			@card.charge_new_card_on_pickup(@order)
			@saved_on_pickup = true
		end

		@products = @customer.user.products
		@categories = Category.recently

		respond_to do |format|
			format.js
		end
	rescue Stripe::CardError => e
		@error = true
		respond_to do |format|
			format.js
		end
	end

	def pay
		@card = Card.find(params[:id])
		Stripe.api_key = @card.customer.user.stripe_secret_key
		@saved = @card.charge_card
		@order = @card.orders.recently.first
		respond_to do |format|
			format.js
		end
	rescue Stripe::CardError => e
		@error = true
		respond_to do |format|
			format.js
		end
	end

	def pickup_pay
		@card = Card.find(params[:id])
		@order = Order.find(params[:order_id])
		Stripe.api_key = @card.customer.user.stripe_secret_key
		@saved = @card.charge_card_on_pickup(@order)
		respond_to do |format|
			format.js
		end
	rescue Stripe::CardError => e
		@error = true
		respond_to do |format|
			format.js
		end
	end

	private
		def card_params
			params.require(:card).permit(:pickup, :order_id, :last4, :brand, :stripe_customer_token, :stripe_card_token, :customer_id)
		end
end

app/helpers/cards_helper.rb
module CardsHelper
	#if customer already has card, hide new card form
	def any_cards(cards)
		"hide hidden-card-form" if cards.any?
	end
end

app/views/cards/_card.html.erb
<div class='card' id="card-<%= card.id %>">
	<%= link_to pay_card_path(card), class: 'pay-card', data: {disable_with: raw("<i class='fa fa-spin fa-spinner'></i>")}, remote: true do %>
		<% if card.brand == "Visa" %>
		  <%= image_tag "visa.png" %>
		<% elsif card.brand == "MasterCard" %>
		  <%= image_tag "master_card.png" %>
		<% elsif card.brand == "Discover" %>
		  <%= image_tag "discover.png" %>
		<% elsif card.brand == "Diners Club" %>
		  <%= image_tag "diners_club.png" %>
		<% elsif card.brand == "JCB" %>
		  <%= image_tag "jcb.png" %>
		<% elsif card.brand == "American Express" %>
		  <%= image_tag "american_express.png" %>
		<% end %>

		<div class="card-last4">
			<%= card.last4 %>
		</div>

		<div style="clear:both;"></div>
	<% end %>

	<!-- destroy card -->
	<%= link_to card_path(card), class: 'destroy-card', method: :delete, remote: true, data: { confirm: "Sure you want to destroy this card?" } do %>
		<i class='fa fa-times'></i>
	<% end %>

</div>

app/views/cards/_pickup_card_payment.html.erb
<%= link_to pickup_pay_card_path(card, order_id:@order.id), class: 'card', data: {disable_with: raw("<i class='fa fa-spin fa-spinner'></i>")}, remote: true do %>
	<% if card.brand == "Visa" %>
	  <%= image_tag "visa.png" %>
	<% elsif card.brand == "MasterCard" %>
	  <%= image_tag "master_card.png" %>
	<% elsif card.brand == "Discover" %>
	  <%= image_tag "discover.png" %>
	<% elsif card.brand == "Diners Club" %>
	  <%= image_tag "diners_club.png" %>
	<% elsif card.brand == "JCB" %>
	  <%= image_tag "jcb.png" %>
	<% elsif card.brand == "American Express" %>
	  <%= image_tag "american_express.png" %>
	<% end %>

	<div class="card-last4">
		<%= card.last4 %>
	</div>

	<div style="clear:both;"></div>
<% end %>

app/views/cards/create.js.erb
<% if @saved_on_dropoff %>
	//reload preloaded products / categories
	$("#preloaded-categories").replaceWith("<%= j render 'layouts/preloaded_categories' %>");
	$(".new-customer-modal").replaceWith("<%= j render 'users/new_customer' %>");

	//hide credit card form modal
	$("#new_card").parent("#modal-overlay").remove();

	//remove toolbar
	if($(".toolbar")[0]){
		$(".toolbar").remove();
	}

	//load receipt, print receipt, and close
	if($('#receipts')[0]){
		$('#receipts').remove();
	}
	$("body").before("<%= j render partial: 'orders/receipt', locals: {receipt_order:@order} %>");
	window.print();


	//scroll to next pick up order if it's present
	if($(".pick-up-order")[0]){
		//close out place order section
		$(".close-place-order, #checkout-category-list").remove();
		$(".place-order-link").show();
		//scroll to next pick up order
		$('html, body').animate({
			scrollTop: $("#show-customer-container").offset().top
		}, 0);
	}else{
		//return open customer to normal state
		$("#show-customer-container").prev(".customer").show();
		$("#show-customer-container").remove();
		$(".search-field").val("").focus();
	}
<% elsif @saved_on_pickup %>
	//reload preloaded products / categories
	$("#preloaded-categories").replaceWith("<%= j render 'layouts/preloaded_categories' %>");
	$(".new-customer-modal").replaceWith("<%= j render 'users/new_customer' %>");

	//remove cc form
	$("#new_card").parent("#modal-overlay").remove();

	//remove unpaid order
	$(".pick-up-order-<%= @order.id %>").fadeOut(function(){
		$(this).remove();

		//scroll to next pick up order if it's present
		if($(".pick-up-order")[0]){
			//close out place order section
			$(".close-place-order, #checkout-category-list").remove();
			$(".place-order-link").show();
			//scroll to next pick up order
			$('html, body').animate({
				scrollTop: $("#show-customer-container").offset().top
			}, 0);
		}else{
			//return open customer to normal state
			$("#show-customer-container").prev(".customer").show();
			$("#show-customer-container").remove();
			$(".search-field").val("").focus();
		}
	});
<% elsif @error %>
	$('#card_number, #card_month, #card_year').val('');
  $('#card_number').focus();
	$("#stripe_error").fadeIn().text("Your card was declined.");
	$("#new_card button").html("Charge Card");
  $('button[type=submit]').attr('disabled', false);
<% end %>

app/views/cards/destroy.js.erb
<% if @destroyed %>
  $("#card-<%= @card.id %>").remove();
<% end %>

app/views/cards/pay.js.erb
<% if @error %>
	$("#stripe_error").fadeIn().text("Your card was declined.");
<% elsif @saved %>
	//hide credit card form modal
	$("#new_card").parent("#modal-overlay").remove();

	//remove toolbar
	if($(".toolbar")[0]){
		$(".toolbar").remove();
	}

	//load receipt, print receipt, and close
	if($('#receipts')[0]){
		$('#receipts').remove();
	}
	$("body").before("<%= j render partial: 'orders/receipt', locals: {receipt_order:@order} %>");
	window.print();


	//scroll to next pick up order if it's present
	if($(".pick-up-order")[0]){
		//close out place order section
		$(".close-place-order, #checkout-category-list").remove();
		$(".place-order-link").show();
		//scroll to next pick up order
		$('html, body').animate({
			scrollTop: $("#show-customer-container").offset().top
		}, 0);
	}else{
		//return open customer to normal state
		$("#show-customer-container").prev(".customer").show();
		$("#show-customer-container").remove();
		$(".search-field").val("").focus();
	}
	
<% end %>

app/views/cards/pickup_pay.js.erb
<% if @error %>
	$("#stripe_error").fadeIn().text("Your card was declined.");
<% elsif @saved %>
	//remove cc form
	$("#new_card").parent("#modal-overlay").remove();

	//remove unpaid order
	$(".pick-up-order-<%= @order.id %>").fadeOut(function(){
		$(this).remove();

		//scroll to next pick up order if it's present
		if($(".pick-up-order")[0]){
			//close out place order section
			$(".close-place-order, #checkout-category-list").remove();
			$(".place-order-link").show();
			//scroll to next pick up order
			$('html, body').animate({
				scrollTop: $("#show-customer-container").offset().top
			}, 0);
		}else{
			//return open customer to normal state
			$("#show-customer-container").prev(".customer").show();
			$("#show-customer-container").remove();
			$(".search-field").val("").focus();
		}
	});
<% end %>