config/routes.rb
Rails.application.routes.draw do
	authenticated :user do
		root to: 'users#show', as: :authenticated_root
	end

	devise_for :users, controllers: { registrations: "users/registrations" } 
	devise_scope :user do
	  get "signin", to: "devise/sessions#new", as: "signin"
	  get "free-trial", to: "users/registrations#new", as: "free_trial"
	end
	resources :users do
		member do
			get 	'tag'
			get 	'rack'
			get 	'remember_rack'
			get		'forget_rack'
			patch 'confirm_password'
			get 	'lost_receipt'
			get 	'read_intro'
			get 	'read_tutorial'
			patch 'set_rack'
		end
	end
	match '/:id/urgent', to: 'users#urgent', via: 'get', as: 'urgent'
	match '/:id/products', to: 'users#products', via: 'get', as: 'user_products'
	match '/:id/employees', to: 'users#employees', via: 'get', as: 'user_employees'
	match '/:id/analytics', to: 'users#analytics', via: 'get', as: 'user_analytics'

	root to: 'pages#home'
	match '/terms', to: 'pages#terms', via: 'get', as: 'terms'

	resources :customers do
		collection { post :import }
		member do
			patch 'update_name'
			patch 'update_phone'
			patch 'update_text'
			patch 'update_starch'
			get 	'place_order'
			get		'details'
			get		'order_history'
			get 	'checkout'
			get		'pay_with_cash'
			get		'productless_item'
			get		'charge_later'
			get 	'pay_with_card'
		end
	end

	resources :products do
		member do
			get 'load_edit'
		end
	end

	resources :categories

	resources :items do
		member do
			patch 'update_price'
		end
	end

	resources :orders do
		member do
			get 	'details'
			get 	'pick_up'
			get 	'search_rack'
			get 	'search_tags'
			get 	'add_order_number'
			get 	'print_receipt'
			patch 'rack'
			get 	'confirm_delete'
			patch 'delete_order'
			get		'pay_on_pickup'
			patch 'leave_note'
			get		'load_urgent_rack'
			patch 'rack_urgent_order'
			get		'pickup_pay_with_cash'
			get		'pickup_pay_with_card'
		end
	end

	resources :cards do
		member do
			get 'pay'
			get 'pickup_pay'
		end
	end

	resources :employees

	resources :checkins do
		member do
			get 	'show_more'
			get 	'change_start_time'
			get 	'change_finish_time'
			patch 'update_start_time'
			patch 'update_finish_time'
		end
	end

	resources :tutorials do
		member do
			get 'open'
		end

		collection do
			post 'sort'
		end
	end
	match '/tutorial', to: 'tutorials#user_tutorial', via: 'get', as: 'user_tutorial'

	resources :messages
end

app/models/checkin.rb
class Checkin < ActiveRecord::Base
	#validations
	validates :employee_id, presence: true

	#relationships
	belongs_to :employee

	#scopes
	scope :recently, -> {order("created_at DESC")}
end

app/controllers/checkins_controller.rb
class CheckinsController < ApplicationController
	def update_start_time
		@checkin = Checkin.find(params[:id])
		@updated = @checkin.update_attributes(checkin_params)
		respond_to do |format|
			format.js
		end
	end

	def update_finish_time
		@checkin = Checkin.find(params[:id])
		@updated = @checkin.update_attributes(checkin_params)
		respond_to do |format|
			format.js
		end
	end

	def change_start_time
		@checkin = Checkin.find(params[:id])
		respond_to do |format|
			format.js
		end
	end

	def change_finish_time
		@checkin = Checkin.find(params[:id])
		respond_to do |format|
			format.js
		end
	end

	def show_more
		@checkin = Checkin.find(params[:id])
		@employee = @checkin.employee
		@index = @employee.checkins.recently.index(@checkin)
		@checkins = @employee.checkins.recently.take(@index+11)
		@height_difference = @employee.checkins.recently.index(@checkins.last)-@index
		respond_to do |format|
			format.js
		end
	end

	def create
		@checkin = Checkin.new(checkin_params)
		@employee = @checkin.employee
		@saved = @checkin.save
		@checkins = @employee.checkins.recently.take(10)
		respond_to do |format|
			format.js
		end
	end

	def update
		@checkin = Checkin.find(params[:id])
		@employee = @checkin.employee
		#record finish time
		@checkin.finish = DateTime.now
		#calculate checkin total
		@checkin.total = TimeDifference.between(@checkin.created_at.to_time, @checkin.finish.to_time).in_hours * @employee.pay_rate
		@updated = @checkin.update_attributes(checkin_params)
		@checkins = @employee.checkins.recently.take(10)
		respond_to do |format|
			format.js
		end
	end

	private
		def checkin_params
			params.require(:checkin).permit(:employee_id, :paid, :finish, :total)
		end
end

app/views/checkins/_change_start_time.html.erb
<%= simple_form_for @checkin, url: update_start_time_checkin_path(@checkin), remote: true do |f| %>
	<%= f.input :created_at, as: :time, ampm: true %>
	<%= f.submit %>
<% end %>

app/views/checkins/_check_out.html.erb
<%= simple_form_for @employee.checkins.where("finish IS NULL").first, remote: true do |f| %>
	<%= f.hidden_field :employee_id, value: @employee.id %>
	<%= f.submit "Check Out", class: "purple-button" %>
<% end %>

app/views/checkins/_checkin.html.erb
<tr class="checkin-<%= checkin.id %> checkin">
	<td><%= checkin.created_at.strftime("%b %_d, %Y") %></td>
	<td class='start-time'>
		<%= checkin.created_at.strftime("%l:%M%P") %>

		<% if false %>
			<!-- comment out ability to change start time / finish time until functionality is complete -->
			<%= link_to raw("<i class='fa fa-clock-o'></i>"), change_start_time_checkin_path(checkin), remote: true %>
		<% end %>

	</td>
	<td class='finish-time'>
		<% unless checkin.finish.blank? %>
			<%= checkin.finish.strftime("%l:%M%P") %>

			<% if false %>
				<!-- comment out ability to change start time / finish time until functionality is complete -->
				<%= link_to raw("<i class='fa fa-clock-o'></i>"), change_finish_time_checkin_path(checkin), remote: true %>
			<% end %>

		<% else %>
			<div class='empty-cell'></div>
		<% end %>
	</td>
	<td>
		<% unless checkin.total.blank? %>
			<%= number_to_currency(checkin.total, precision: (checkin.total.round == checkin.total) ? 0 : 2) %>
		<% else %>
			<div class="empty-cell"></div>
		<% end %>
	</td>
</tr>

app/views/checkins/_new_checkin.html.erb
<%= simple_form_for Checkin.new, remote: true do |f| %>
	<%= f.hidden_field :employee_id, value: @employee.id %>
	<%= f.submit "Check In", class: "black-button" %>
<% end %>

app/views/checkins/change_finish_time.js.erb
//load form to edit start time
$(".checkin-<%= @checkin.id %> .finish-time").html("<%= j render 'checkins/change_start_time' %>");

app/views/checkins/change_start_time.js.erb
//load form to edit start time
$(".checkin-<%= @checkin.id %> .start-time").html("<%= j render 'checkins/change_start_time' %>");

app/views/checkins/create.js.erb
<% if @saved %>
	$("#timesheet").replaceWith("<%= j render 'employees/timesheet' %>");
<% end %>

app/views/checkins/show_more.js.erb
//add more checkins to checkin list
$("#timesheet").replaceWith("<%= j render 'employees/timesheet' %>");

var y = $(window).scrollTop();

$('html, body').animate({
	scrollTop: (y+<%= @height_difference * 49 %>)
}, 150);

app/views/checkins/update.js.erb
<% if @updated %>
	$("#timesheet").replaceWith("<%= j render 'employees/timesheet' %>");
<% end %>